# Generated by Django 4.2.6 on 2023-10-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='organization',
        ),
        migrations.AddField(
            model_name='organization',
            name='admin_name',
            field=models.CharField(default='DefaultAdminName', max_length=100),
        ),
        migrations.AddField(
            model_name='organization',
            name='team_member_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.DeleteModel(
            name='OrganizationAdmin',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
