# Generated by Django 4.2.6 on 2023-10-15 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0005_organization_latitude_organization_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
    ]
