# Generated by Django 4.2.6 on 2023-10-15 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0006_alter_organization_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='name',
            new_name='Organization_name',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='type',
            new_name='Organization_type',
        ),
    ]
