# Generated by Django 4.2.6 on 2023-10-15 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0007_rename_name_organization_organization_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='location',
            new_name='Organization_location',
        ),
    ]
