# Generated by Django 4.2.6 on 2023-10-16 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0010_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
