# Generated by Django 4.2.6 on 2024-02-01 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255)),
                ('organization_type', models.CharField(choices=[('flood', 'Disaster - Flooding'), ('earthquake', 'Disaster - Earthquake'), ('tsunami', 'Disaster - Tsunami'), ('cyclone', 'Disaster - Cyclone'), ('wildfire', 'Disaster - Wildfire'), ('other', 'Other')], max_length=20)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('team_members_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('role', models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('helper', 'Helper'), ('fighter', 'Fighter')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RescueOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pointer.organization')),
            ],
        ),
    ]
