# Generated by Django 4.2.6 on 2024-02-03 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pointer', '0003_userlocation_address_userlocation_organization_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlocation',
            name='user',
        ),
    ]
