# Generated by Django 4.2.6 on 2024-01-21 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teamformation', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DisasterInfo',
        ),
    ]
