# Generated by Django 4.1.2 on 2024-01-28 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_connection_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='team_count',
        ),
    ]
