# Generated by Django 4.1.2 on 2024-01-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Org_pincode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, choices=[('ariyalur', 'Ariyalur'), ('chennai', 'Chennai'), ('coimbatore', 'Coimbatore'), ('cuddalore', 'Cuddalore'), ('dharmapuri', 'Dharmapuri'), ('dindigul', 'Dindigul'), ('erode', 'Erode'), ('kanchipuram', 'Kanchipuram'), ('kanyakumari', 'Kanyakumari'), ('karur', 'Karur'), ('krishnagiri', 'Krishnagiri'), ('madurai', 'Madurai'), ('nagapattinam', 'Nagapattinam'), ('namakkal', 'Namakkal'), ('perambalur', 'Perambalur'), ('pudukkottai', 'Pudukkottai'), ('ramanathapuram', 'Ramanathapuram'), ('salem', 'Salem'), ('sivagangai', 'Sivagangai'), ('thanjavur', 'Thanjavur'), ('theni', 'Theni'), ('thiruvallur', 'Thiruvallur'), ('thiruvarur', 'Thiruvarur'), ('thoothukudi', 'Thoothukudi'), ('tiruchirappalli', 'Tiruchirappalli'), ('tirunelveli', 'Tirunelveli'), ('tiruppur', 'Tiruppur'), ('trichy', 'Trichy'), ('tuticorin', 'Tuticorin'), ('vellore', 'Vellore'), ('villupuram', 'Villupuram'), ('virudhunagar', 'Virudhunagar')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization_type',
            field=models.CharField(blank=True, choices=[('medical', 'Medical'), ('tsunami', 'Tsunami'), ('flood', 'Flood'), ('cyclone', 'Cyclone'), ('Earth Quake', 'Earth Quake'), ('storm', 'Storm'), ('other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
