# Generated by Django 4.2.6 on 2024-02-16 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_user_date_of_birth_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
    ]
